# https://taskfile.dev

version: '3'


tasks:
  upgrade:
      cmds:
        - uv lock --upgrade
        - uv sync
  update:
    dir: ./docs
    cmds:
      - git pull
  dev:
    cmds:
      - uv run mkdocs serve
  dirty:
    cmds:
        - uv run mkdocs serve --dirty
  watch:
    cmds:
      - uv run mkdocs serve --watch ./overrides/