name: Repository maintenance
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  maintenance:
    uses: Enveloppe/wiki/.github/workflows/maintenance.yml@main
    with:
      BRANCH: main
      CLEAN: true
      UPDATE_REQUIREMENTS: true
      OPTIMIZE_IMAGES: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      AUTHOR_EMAIL: ${{ 'github-actions[bot]@users.noreply.github.com' }}
      AUTHOR_NAME: ${{ 'github-actions[bot]' }}
  deploy:
    uses: Mara-Li/wiki/.github/workflows/deploy.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      