name: Update requirement
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
            enable-cache: true
            cache-dependency-glob: "requirements**.txt"
      - name: Setup Python
        run: uv python install
      - name: Install dependencies
        run: |
          uv venv
          uv sync
          uv add pur --dev
      - name: purr
        run: uv run pur -r requirements.txt
      - name: Update venv
        run: |
          uv pip install -r requirements.txt
          uv sync
          uv lock --upgrade
      - name: Commit changes
        continue-on-error: true
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git add requirements.txt
          git commit -m "chore (update): requirements.txt"
          git push
      - name: deploy
        run: uv run mkdocs gh-deploy --force
